# Generated by Django 3.2.8 on 2021-10-20 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200, unique=True)),
                ('level', models.CharField(choices=[(1, 'User'), (2, 'Admin'), (3, 'Owner')], max_length=1)),
            ],
        ),
    ]
