# Generated by Django 3.2.8 on 2021-10-20 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_person_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='level',
            field=models.IntegerField(choices=[('User', 1), ('Admin', 2), ('Owner', 3)]),
        ),
    ]
