# Generated by Django 3.2.8 on 2021-10-20 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_person_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='level',
            field=models.IntegerField(choices=[(1, 'User'), (2, 'Admin'), (3, 'Owner')]),
        ),
    ]
