# Generated by Django 3.2.8 on 2021-10-20 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_person_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='level',
            field=models.CharField(choices=[(1, 'User'), (2, 'Admin'), (3, 'Owner')], max_length=5),
        ),
    ]
