# Generated by Django 3.2.8 on 2021-10-20 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_person_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.CharField(max_length=1000)),
                ('level', models.IntegerField(choices=[(1, 'User'), (2, 'Admin'), (3, 'Owner')])),
            ],
        ),
    ]
