# Generated by Django 3.2.8 on 2021-10-21 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_information'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Information',
        ),
        migrations.AlterField(
            model_name='person',
            name='level',
            field=models.IntegerField(choices=[(1, 'Usuário'), (2, 'Admin'), (3, 'Dono')]),
        ),
    ]
